-- Add deduplication and normalization fields to alerts table
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS severity TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS environment TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS service TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS resource TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS occurrence_count INTEGER NOT NULL DEFAULT 1;
